/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package desarrollodeinterfaces.ProyectoAPP.vista;

import desarrollodeinterfaces.ProyectoAPP.modelo.Usuario;
import desarrollodeinterfaces.ProyectoAPP.controller.UsuarioController;
import desarrollodeinterfaces.ProyectoAPP.vista.Inicio;
import desarrollodeinterfaces.ProyectoAPP.vista.Inicio;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author joses
 */
public class Registrarse extends javax.swing.JDialog {

    /**
     * Creates new form Registrarse
     */
    public Registrarse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Registrarse(){
        initComponents();
        transparenteValidation();
        
        ButtonAceptar.setEnabled(false);
        ValidationGroup group=validationPanel1.getValidationGroup();
        
        group.add(TextFieldUsuario, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(TextFieldContrasena,StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(TextFieldEdad, StringValidators.REQUIRE_NON_NEGATIVE_NUMBER,StringValidators.REQUIRE_VALID_INTEGER);
        group.add(TextFieldRepetirContrasena,StringValidators.REQUIRE_NON_EMPTY_STRING);
        
        
        validationPanel1.addChangeListener(new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e){
                if (validationPanel1.getProblem()==null)
                    ButtonAceptar.setEnabled(true);
                else
                    ButtonAceptar.setEnabled(false);
            }
        });
    }
    
    
     public void transparenteValidation(){
       validationPanel1.setOpaque(false);
      
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        LabelUsuario = new javax.swing.JLabel();
        TextFieldUsuario = new javax.swing.JTextField();
        LabelContrasena = new javax.swing.JLabel();
        TextFieldContrasena = new javax.swing.JTextField();
        LabelRepetirContrasena = new javax.swing.JLabel();
        TextFieldRepetirContrasena = new javax.swing.JTextField();
        LabelEdad = new javax.swing.JLabel();
        TextFieldEdad = new javax.swing.JTextField();
        ButtonVolver = new javax.swing.JButton();
        ButtonAceptar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        validationPanel1.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jPanel1.add(validationPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, 70));

        LabelUsuario.setFont(new java.awt.Font("Cascadia Mono", 0, 15)); // NOI18N
        LabelUsuario.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.LabelUsuario.text")); // NOI18N
        jPanel1.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 80, 40));

        TextFieldUsuario.setFont(new java.awt.Font("Cascadia Mono", 1, 22)); // NOI18N
        TextFieldUsuario.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.TextFieldUsuario.text")); // NOI18N
        jPanel1.add(TextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 190, 40));

        LabelContrasena.setFont(new java.awt.Font("Cascadia Mono", 0, 15)); // NOI18N
        LabelContrasena.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.LabelContrasena.text")); // NOI18N
        jPanel1.add(LabelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, 40));

        TextFieldContrasena.setFont(new java.awt.Font("Cascadia Mono", 1, 22)); // NOI18N
        TextFieldContrasena.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.TextFieldContrasena.text")); // NOI18N
        jPanel1.add(TextFieldContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 190, 40));

        LabelRepetirContrasena.setFont(new java.awt.Font("Cascadia Code", 0, 15)); // NOI18N
        LabelRepetirContrasena.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.LabelRepetirContrasena.text")); // NOI18N
        jPanel1.add(LabelRepetirContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 40));

        TextFieldRepetirContrasena.setFont(new java.awt.Font("Cascadia Mono", 1, 22)); // NOI18N
        TextFieldRepetirContrasena.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.TextFieldRepetirContrasena.text")); // NOI18N
        TextFieldRepetirContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRepetirContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldRepetirContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 190, 40));

        LabelEdad.setFont(new java.awt.Font("Cascadia Mono", 0, 15)); // NOI18N
        LabelEdad.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.LabelEdad.text")); // NOI18N
        jPanel1.add(LabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 50, 30));

        TextFieldEdad.setFont(new java.awt.Font("Cascadia Mono", 1, 22)); // NOI18N
        TextFieldEdad.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.TextFieldEdad.text")); // NOI18N
        jPanel1.add(TextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 190, 40));

        ButtonVolver.setFont(new java.awt.Font("Cascadia Mono", 0, 15)); // NOI18N
        ButtonVolver.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.ButtonVolver.text")); // NOI18N
        ButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        ButtonAceptar.setFont(new java.awt.Font("Cascadia Mono", 0, 15)); // NOI18N
        ButtonAceptar.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.ButtonAceptar.text")); // NOI18N
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desarrollodeinterfaces/ProyectoAPP/imagenIniciarSesionTamaño.jpg"))); // NOI18N
        Fondo.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.Fondo.text")); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldRepetirContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRepetirContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRepetirContrasenaActionPerformed

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
       
        if(TextFieldContrasena.getText().equals(TextFieldRepetirContrasena.getText())){
             Usuario u1 = new Usuario();
        u1.setId(0);
        u1.setUsuario(TextFieldUsuario.getText());
        u1.setContrasena(TextFieldContrasena.getText());
        u1.setEdad(Integer.parseInt(TextFieldEdad.getText()));
        
        UsuarioController.crearUsuario(u1);
        
        IniciarSesion is=new IniciarSesion();
        is.setVisible(true);
        
        dispose();
        
        }else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no son iguales", "Intentelo de nuevo", JOptionPane.INFORMATION_MESSAGE);
        }
        
       
        
        
        
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    private void ButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVolverActionPerformed
        Inicio i1=new Inicio();
        i1.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registrarse dialog = new Registrarse(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonVolver;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LabelContrasena;
    private javax.swing.JLabel LabelEdad;
    private javax.swing.JLabel LabelRepetirContrasena;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JTextField TextFieldContrasena;
    private javax.swing.JTextField TextFieldEdad;
    private javax.swing.JTextField TextFieldRepetirContrasena;
    private javax.swing.JTextField TextFieldUsuario;
    private javax.swing.JPanel jPanel1;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
