/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package desarrollodeinterfaces.ProyectoAPP.vista;

import desarrollodeinterfaces.ProyectoAPP.controller.SonidoController;
import desarrollodeinterfaces.ProyectoAPP.modelo.Sonido;



/**
 *
 * @author joses
 */
public class Volcan extends javax.swing.JDialog {

    /**
     * Creates new form Volcan
     */
    public Volcan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
  public Volcan() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        BotonMoltres = new javax.swing.JButton();
        BotonCharizard = new javax.swing.JButton();
        BotonGroudon = new javax.swing.JButton();
        BotonCyndaquil = new javax.swing.JButton();
        BotonMagcargo = new javax.swing.JButton();
        BotonBlaziken = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desarrollodeinterfaces/ProyectoAPP/volcanFinalTamaño.jpg"))); // NOI18N
        Fondo.setText(org.openide.util.NbBundle.getMessage(Volcan.class, "Volcan.Fondo.text")); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        BotonVolver.setText(org.openide.util.NbBundle.getMessage(Volcan.class, "Volcan.BotonVolver.text")); // NOI18N
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 70));

        BotonMoltres.setText(org.openide.util.NbBundle.getMessage(Volcan.class, "Volcan.BotonMoltres.text")); // NOI18N
        BotonMoltres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMoltresActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMoltres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 29, 230, 170));

        BotonCharizard.setText(org.openide.util.NbBundle.getMessage(Volcan.class, "Volcan.BotonCharizard.text")); // NOI18N
        BotonCharizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCharizardActionPerformed(evt);
            }
        });
        jPanel1.add(BotonCharizard, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 300, 220));

        BotonGroudon.setText(org.openide.util.NbBundle.getMessage(Volcan.class, "Volcan.BotonGroudon.text")); // NOI18N
        BotonGroudon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGroudonActionPerformed(evt);
            }
        });
        jPanel1.add(BotonGroudon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 449, 360, 280));

        BotonCyndaquil.setText(org.openide.util.NbBundle.getMessage(Volcan.class, "Volcan.BotonCyndaquil.text")); // NOI18N
        BotonCyndaquil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCyndaquilActionPerformed(evt);
            }
        });
        jPanel1.add(BotonCyndaquil, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 619, 60, 60));

        BotonMagcargo.setText(org.openide.util.NbBundle.getMessage(Volcan.class, "Volcan.BotonMagcargo.text")); // NOI18N
        BotonMagcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMagcargoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMagcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 459, 120, 150));

        BotonBlaziken.setText(org.openide.util.NbBundle.getMessage(Volcan.class, "Volcan.BotonBlaziken.text")); // NOI18N
        BotonBlaziken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBlazikenActionPerformed(evt);
            }
        });
        jPanel1.add(BotonBlaziken, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 140, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMoltresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMoltresActionPerformed
        SonidoController.playSE(1);
    }//GEN-LAST:event_BotonMoltresActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        ElegirZona ez1= new ElegirZona();
        ez1.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonCharizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCharizardActionPerformed
        SonidoController.playSE(2);
       
    }//GEN-LAST:event_BotonCharizardActionPerformed

    private void BotonGroudonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGroudonActionPerformed
        SonidoController.playSE(3);
    }//GEN-LAST:event_BotonGroudonActionPerformed

    private void BotonCyndaquilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCyndaquilActionPerformed
        SonidoController.playSE(4);
    }//GEN-LAST:event_BotonCyndaquilActionPerformed

    private void BotonMagcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMagcargoActionPerformed
        SonidoController.playSE(5);
    }//GEN-LAST:event_BotonMagcargoActionPerformed

    private void BotonBlazikenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBlazikenActionPerformed
        SonidoController.playSE(6);
    }//GEN-LAST:event_BotonBlazikenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volcan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volcan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volcan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volcan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Volcan dialog = new Volcan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBlaziken;
    private javax.swing.JButton BotonCharizard;
    private javax.swing.JButton BotonCyndaquil;
    private javax.swing.JButton BotonGroudon;
    private javax.swing.JButton BotonMagcargo;
    private javax.swing.JButton BotonMoltres;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
